name: Auto pullback
on:
  push:
    branches:
      - 'production'
jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Merge production -> staging
        uses: devmasx/merge-branch@v1.3.1
        with:
          type: now
          target_branch: staging
          github_token: ${{ github.token }}
      
      - name: Alert slack on error
        uses: rtCamp/action-slack-notify@v2
        with:
          status: ${{ job.status }}
          notify_when: 'failure'
        env:
          SLACK_WEBHOOK: ${{ secrets.AUTO_PULLBACK_SLACK_WEBHOOK }}
          SLACK_MESSAGE: 'Could not automatically pullback production to staging, please could someone resolve this manually'  
