on:
  issues:
    types: [opened, edited]

jobs:
  enforce_issue_template_job:
    runs-on: ubuntu-latest
    name: A job to enforce issue templates
    steps:
      - name: Check issue
        uses: mattlewis92/matts-bot@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
